version: "3.4"
services:
 vite_docker:
   image: node:alpine
   container_name: frontend-shopee-mini
   entrypoint: /bin/sh
   ports:
     - 80:80
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true