// export { default as adminAccountReducer } from "./admin/account/accountSlice"
export { default as adminCategoriesReducer } from "./admin/categories/categoriesSlice"
export { default as adminProductsReducer } from "./admin/products/productsSlice"
export { default as adminBrandsReducer } from "./admin/brands/brandsSlice"
export { default as productsReducer } from "./client/products/productsSlice"
export { default as categoriesReducer } from "./client/categories/categoriesSlice"
export { default as brandsReducer } from "./client/brands/brandsSlice"
export { default as accountReducer } from "./client/account/accountSlice"
export { default as cartsReducer } from "./client/carts/cartsSlice"
export { default as orderReducer } from "./client/orders/orderSlice"
export { default as adminUsers } from "./admin/account/accountSlice"
export { default as adminOrders } from "./admin/orders/orderSlice"
export { default as adminDashboard } from "./admin/dashboard/dashboardSlice"