export const brandsInitState = {
    isError: false,
    isLoading: true,
    results: [],
    currentPage: 1,
    totalPage: 1,
    status: "",
    formInput: {
        id: "",
        name: "",
        imagePreview: [],
    },
    isCreate: false,
    isUpdate: false,
    isDelete: false,
    loadingMessage: "",
    successMessage: "",
    errorMessage: "",
    toastLoading: false,
    toastSuccess: false,
    toastError: false,
}